version: '3'

services: 
  jasperserver:
    image: local/jasperserver:7.1.1
    container_name: jasperserver
    hostname: jasperserver
    networks: 
      - docker-local
    ports: 
      - 8080:8080
    environment: 
      DB_TYPE: mysql
      DB_HOST: hive-metastore
      DB_NAME: jasperserver
      DB_PASSWORD: p4ssW0rd
      DB_PORT: 3306
      DB_USER: jasperserver
      
networks:
  docker-local:
    external: true
